--- #YAML:1.0
name:                Algorithm-RandomMatrixGeneration
version:             0.05
abstract:            Perl module to generate matrix given the marginals.
license:             gpl
author:              
    - Anagha Kulkarni <anaghak at cs.cmu.edu>, Ted Pedersen <tpederse at d.umn.edu>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
